version: "3"

services:
  web:
    restart: "always"
    build: .
    # environment:
    #   IP: 41.59.88.233
    command: bash -c "gunicorn --bind 0.0.0.0:8000 project_m_n_e_service.wsgi"
    container_name: authentications
    image: authentications
    working_dir: /authentications
    volumes:
      - ./authentications

    ports:
      - "8000:8000"
    # depends_on:
    #   - db
      # - redis